language: node_js
node_js:
  - "4.2.2"
  - "4.2.1"
services:
  - redis-server
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
